### PR TITLE
Issue #35 prepending the application environment rootURL to the asset map relative path to fix the relative path problem

### PR DESCRIPTION
**Pull request by aneeshcentrica**
fix for assetmap file is loaded through a relative path which fails when you land on a nested route

### CODE REVIEW

**Comment by RuslanZavacky** [comment]
@aneeshcentrica can you please check why tests are failing?

**Comment by RuslanZavacky** [comment]
Also, can you please remove package-json.lock file.

**Comment by icole** [comment]
I ran into this issue as well and used the proposed change which seems to fix things when deployed in production, but when running ember in development or test mode it doesn't seem work with the absolute pathing. Here is a proposed workaround that passes the tests (https://github.com/icole/ember-cli-ifa/commit/b16910ffad2280c1269e09e80cf71c1f3c241dcc). I didn't want to hijack @aneeshcentrica's pull request so I figured the change could be made to this existing PR by the author. @RuslanZavacky if this looks ok to you and you would prefer me to open a new PR let me know

**Comment by RuslanZavacky** [comment]
I'll close this one and if problem still persist, will try to solve it separately. Thanks @aneeshcentrica

**Comment by wopian** [comment]
This appears to still be a problem for me. Recently added `ember-cli-ifa` and ran into this issue of relative URLs, breaking on almost all of the app's routes:

`/settings/profile` requests:
- `/settings/assets/assetMap-40cf06cb47daefca3e09c451815d1e51.json`

Whereas it exists in:
- `/assets/assetMap-40cf06cb47daefca3e09c451815d1e51.json`

`fingerprint: { prepend: '/' }` isn't a workable solution in my case.

**Pull request closed without merging**
