### PR TITLE
Fix DEPRECIATION for lookupFactory

### PR DESCRIPTION
**Pull request by BnitoBzh**

### CODE REVIEW

**Comment by RuslanZavacky** [comment]
Thank you @BnitoBzh :)

**Comment by BnitoBzh** [comment]
You're welcome! Don't hesitate to push a new version like 0.5.1

**Comment by BnitoBzh** [comment]
No ?

**Comment by RuslanZavacky** [comment]
@BnitoBzh sorry, I was slow on this one.. published :)

**Pull request merged**
