### PR TITLE
Turn initializer into an instance initializer

### PR DESCRIPTION
**Pull request by zeppelin**
Ensures Fastboot compatibility, since Fastboot only has `app.__container__` on app instances. I guess `app.__container__` is for backwards compatibility from the era where initializers didn't exist.

Minor gotcha: if someone is `import`ing the initializer directly, this is breaking change.

### CODE REVIEW

**Comment by zeppelin** [comment]
Please don't merge until I investigate why subsequent rebuilds fail to inject the asset map value when `inline`.

**Comment by RuslanZavacky** [comment]
Hey @zeppelin, thanks for this change. I have some questions around it. I think using initializer instead of instance-initializer was deliberate, as assets-map is not gonna change after an app is loaded, though in the fastboot word (If I remember correctly) will be loaded only once.

Also, in the initializer, you have an ability to defer loading, which is useful, if your design needs some files from the asset map. Without the defer, you'll have 'flashed' content, eg. without the asset, and then when the asset will load, it will appear.

Have you been able to tackle, if it's working fine for you as instance-initializer?

**Comment by zeppelin** [comment]
There are multiple issues with using an instance-initializer, but I can't seem to get it working with Fastboot any other way. I'll definitely investigate, because I'd rather use the official package than to constantly udate my fork.

**Comment by zeppelin** [comment]
Unfortunetly the solution to get full FastBoot-support is more complicated than this. Closing.

**Pull request closed without merging**
