### PR TITLE
fix factoryFor error

### PR DESCRIPTION
**Pull request by BnitoBzh**
Fix of the error below : 

You attempted to access "ifa" on a factory manager created by container#factoryFor. "ifa" is not a member of a factory manager."

### CODE REVIEW

**Comment by BnitoBzh** [comment]
tr

**Comment by BnitoBzh** [comment]
Please merge this hotfix without forget to change the current version, like 0.5.2. Thanks in advance!

**Comment by RuslanZavacky** [comment]
Thank you @BnitoBzh :)

**Comment by BnitoBzh** [comment]
You're welcome! Don't forget to push the new minor version 0.5.2 ;)

**Comment by RuslanZavacky** [comment]
@BnitoBzh released, should be good :)

**Pull request merged**
